---
- name: "Ansible Playbook to install a Zookeeper ensemble and Kafka Broker Authenticated"
  hosts: all
  remote_user: rhmw
  #serial: 1
  vars_files:
    - vars.yml
  collections:
    - redhat.amq_streams
  roles:
    - role: amq_streams_zookeeper
    - role: amq_streams_broker

  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count_enabled is defined and amq_streams_zookeeper_instance_count_enabled

    - name: "Display numbers of broker instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of broker instances: {{ amq_streams_broker_instance_count }}."
      when:
        - amq_streams_broker_instance_count_enabled is defined and amq_streams_broker_instance_count_enabled

    - name: "Validate that Zookeeper deployment is functional."
      ansible.builtin.include_role:
        name: redhat.amq_streams.amq_streams_zookeeper
        tasks_from: validate.yml

    - name: "Validate that Broker deployment is functional."
      ansible.builtin.include_role:
        name: redhat.amq_streams.amq_streams_broker
        tasks_from: validate.yml
